name: ubios

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt all packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly # support 2024 edition rustfmt checks
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build-ubios:
    name: Build ubios
    runs-on: ubuntu-latest
    needs: fmt
    strategy:
      matrix:
        TOOLCHAIN: [nightly]
        TARGET: [
          riscv64gc-unknown-linux-gnu,
          x86_64-unknown-linux-gnu,
          aarch64-unknown-linux-gnu
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.TARGET }}
          toolchain: ${{ matrix.TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.TARGET }}
      - name: Build
        run: |
          cargo build -p ubios --target ${{ matrix.TARGET }} --verbose

  test-ubios:
    name: Test ubios
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          cargo test -p ubios --verbose

